name: TestsAndDeploy

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytz
    - name: Analysing the code with pylint
      run: |
        PYTHONPATH=$PYTHONPATH:. pylint --disable C0116,C0114,C0115,C0103,C0325 --max-line-length=200 `ls -R|grep .py$|xargs`

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Running tests with pytest
      run: |
        python -m pytest ./tests/*

  deploy:
    needs: [lint, tests]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deploy/requirements.txt
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -yq install zip
    - name: Deploy version to serverless
      env:
          service_account_key_id: ${{ secrets.SERVICE_ACCOUNT_KEY_ID }}
          SERVICE_ACCOUNT_ID: ${{ secrets.SERVICE_ACCOUNT_ID }}
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
          TARGET_FUNCTION_ID: ${{ secrets.TARGET_FUNCTION_ID }}
          REMINDER_FUNCTION_ID: ${{ secrets.REMINDER_FUNCTION_ID }}
      run: |
        zip -r bot.zip ./bot.py ./requirements.txt ./lib
        zip -r ./reminder.zip ./requirements.txt ./reminder.py ./lib
        python ./deploy/deploy.py