name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytz
    - name: Analysing the code with pylint
      run: |
        PYTHONPATH=$PYTHONPATH:. pylint --disable C0116,C0114,C0115,C0103,C0325 --max-line-length=200 `ls -R|grep .py$|xargs`
